version: '3.8'

services:
  angular:
    build:
      context: ./angular-app
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
