version: '3.8'

services:
  angular:
    build:
      context: ./angular-app
    ports:
      - "80:80"
    networks:
      - app-network

  php:
    build:
      context: ./php-app
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./php-app/.env
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
