services:
  frontend:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - amb-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=central;Username=postgres;Password=root
    depends_on:
      - postgres
    networks:
      - amb-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=central
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - amb-network

volumes:
  postgres-data:
  node_modules:

networks:
  amb-network:
